apiVersion: batch/v1
kind: Job
metadata:
  name: git-create-repo-job
  namespace: gitea
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 3
  template:
    metadata:
      name: git-create-repo-job
    spec:
      restartPolicy: Never
      containers:
        - name: git-create-repo-job
          image: curlimages/curl
          env:
            - name: GIT_SERVICE
              value: "gitea-http.gitea.svc.cluster.local"
            - name: GIT_SERVICE_PORT
              value: "3000"
            - name: GIT_USERNAME
              value: "gitea_admin"
            - name: GIT_PASSWORD
              value: "gitea_admin"
          command:
            - /bin/sh
            - -c
            - |
              curl -X 'POST' "http://$GIT_SERVICE:$GIT_SERVICE_PORT/api/v1/user/repos" \
                -u "$GIT_USERNAME:$GIT_PASSWORD"  \
                -H 'Content-Type: application/json' \
                -d '{
                   "default_branch": "main",
                   "description": "software-templates",
                   "name": "software-templates",
                   "private": false,
                   "readme": "Janus IDP software-templates"
                 }'
              
              curl -X 'POST' "http://$GIT_SERVICE:$GIT_SERVICE_PORT/api/v1/user/repos" \
                -u "$GIT_USERNAME:$GIT_PASSWORD"  \
                -H 'Content-Type: application/json' \
                -d '{
                    "default_branch": "main",
                    "description": "backstage-catalog-entities",
                    "name": "backstage-catalog-entities",
                    "private": false,
                    "readme": "Janus IDP catalog entities"
                  }'
