apiVersion: v2
name: helm-janus-idp
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x