apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: janus-idp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc
    namespace: idp
  sources:
    - repoURL: 'https://janus-idp.github.io/helm-backstage'
      chart: backstage
      targetRevision: 2.6.0
      #repoURL: 'https://github.com/janus-idp/helm-backstage.git'
      #targetRevision: backstage-2.6.0
      #path: charts/backstage
      helm:
        valueFiles:
        - $values/local/values/janus-idp.yml
    - repoURL: 'https://github.com/ch007m/my-janus.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://github.com/ch007m/my-janus.git'
      targetRevision: main
      path: charts/janus-idp