apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: keycloak
      targetRevision: 17.0.1
      helm:
        valueFiles:
          - $values/local-kind/helm-values/keycloak.yml
    - repoURL: 'https://github.com/ch007m/my-janus.git'
      targetRevision: main
      ref: values