apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: keycloak
      targetRevision: 22.0.4
      helm:
        valueFiles:
          - $values/charts/keycloak/values.yml
    - repoURL: 'https://github.com/ch007m/my-janus.git'
      targetRevision: main
      ref: values