apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: janus-idp
data:
  app-config.yaml: |-
    organization:
      name: "Janus IDP"
    backend:
      auth:
        keys:
          - secret: temp
      database:
        client: better-sqlite3
        connection: ':memory:'
      reading:
        allow:
          - host: gitea.localtest.me
    techdocs:
      builder: 'local' # Alternatives - 'external'
      generator:
        runIn: 'local' # Alternatives - 'local'
      publisher:
        type: 'local'
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - url: https://kubernetes.default.svc
              name: kind
              authProvider: 'serviceAccount'
              skipTLSVerify: true
              skipMetricsLookup: true
              serviceAccountToken: /var/run/secrets/kubernetes.io/serviceaccount/token
    catalog:
      import:
        entityFilename: catalog-info.yaml
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API]
      locations:
        - type: url
          target: https://gitea.localtest.me:8443/gitea_admin/catalog-entities/src/branch/main/catalog-entities/all.yaml
          rules:
            - allow: [Template]
        - type: url
          target: https://gitea.localtest.me:8443/gitea_admin/software-templates/src/branch/gitea/showcase-templates.yaml
          rules:
            - allow: [Template]
    integrations:
      gitea: 
      - host: gitea.localtest.me:8443
        username: "gitea_admin"
        password: "gitea_admin"
