apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: janus-idp
data:
  app-config.yaml: |- 
    organization:
      name: "Janus IDP"
    app:
      baseUrl: 'https://janus-idp.localtest.me:8443' 
    backend:
      auth:
        keys:
          - secret: temp
      baseUrl: 'https://janus-idp.localtest.me:8443'
      cors:
        origin: 'https://janus-idp.localtest.me:8443'
      database:
        client: better-sqlite3
        connection: ':memory:'
      reading:
        allow:
          - host: '*.localtest.me:8443' # gitea-http.gitea.svc.cluster.local:3000
    techdocs:
      builder: 'local' # Alternatives - 'external'
      generator:
        runIn: 'local' # Alternatives - 'local'
      publisher:
        type: 'local'
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - url: https://kubernetes.default.svc
              name: kind
              authProvider: 'serviceAccount'
              skipTLSVerify: true
              skipMetricsLookup: true
              serviceAccountToken: /var/run/secrets/kubernetes.io/serviceaccount/token
    catalog:
      import:
        entityFilename: catalog-info.yaml
      rules:
      - allow: [Component, Domain, System, Group, Resource, Location, Template, API]
      locations:
      - type: url
        target: http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/catalog-entities/raw/branch/main/catalog-entities/all.yaml #https://gitea.localtest.me:8443/gitea_admin/catalog-entities/raw/branch/main/catalog-entities/all.yaml
        rules:
          - allow: [Template]
      - type: url
        target: http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/catalog-entities/raw/branch/gitea/showcase-templates.yaml #https://gitea.localtest.me:8443/gitea_admin/software-templates/raw/branch/gitea/showcase-templates.yaml
        rules:
          - allow: [Template]
    integrations:
      gitea: 
      - host: gitea-http.gitea.svc.cluster.local:3000 # gitea-http.gitea.svc.cluster.local:3000
        baseUrl: "http://gitea-http.gitea.svc.cluster.local:3000"
        username: "gitea_admin"
        password: "gitea_admin"
