apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    # cluster API URL
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: v1.13.1
      helm:
        valuesObject:
          installCRDs: true
        #valueFiles:
        #- $values/local/values/cert-manager.yml
    #- repoURL: 'https://github.com/ch007m/my-janus.git'
    #  targetRevision: main
    #  ref: values
    - repoURL: https://github.com/ch007m/my-janus.git
      targetRevision: main
      path: argocd/cert-manager