apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: janus-idp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: {{ .Values.spec.project.name }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: janus-idp
  sources:
    - repoURL: https://github.com/ch007m/my-janus.git
      targetRevision: main
      path: argocd/janus-idp
    - repoURL: 'https://janus-idp.github.io/helm-backstage'
      chart: backstage
      targetRevision: 2.6.0
      helm:
        valuesObject:
          upstream:
            backstage:
              image:
                registry: quay.io/ch007m
                repository: janus-idp
                tag: latest
              extraEnvVars:
                - name: 'NODE_TLS_REJECT_UNAUTHORIZED'
                  value: 0
              extraAppConfig:
                - filename: app-config.yaml
                  configMapRef: app-config
            ingress:
              enabled: true
              host: janus-idp.localtest.me
          route:
            enabled: false